name: Metrics
on:
  schedule:
    - cron: "0 2-23/2 * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'alexsobiek/alexsobiek'"
    steps:  
      - name: "Most Used Languages"
        uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_ignored: html, css                          # List of languages to ignore
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                               # Hides all languages less than 2%
          plugin_languages_limit: 8                                    # Display up to 8 languages
      - name: "Isometric Calendar"
        uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Display half year instead of full year
